### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by eboto** [benlings/scala-guice#3]
I can't build the project.

Is there some additional build instruction that I'm just not getting? It seems as if guide should be on the compile path but is not. Doesn't help I suppose that I'm not very familiar with sbt.

```
(eboto@EremMBP)-(~/code/scala-guice)
(01/23/2012 16:35:24)-> ./sbt
[info] Building project Scala Guice 0.1 against Scala 2.9.0-1
[info]    using ScalaGuice with sbt 0.7.7 and Scala 2.7.7
> compile
[info] 
[info] == compile ==
[info]   Source analysis: 6 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling main sources...
[error] /Users/eboto/code/scala-guice/src/main/scala/BindingExtensions.scala:18: object google is not a member of package com
[error] import com.google.inject._
[error]            ^
[error] /Users/eboto/code/scala-guice/src/main/scala/InjectorExtensions.scala:18: object google is not a member of package com
[error] import com.google.inject.Injector
[error]            ^
[error] /Users/eboto/code/scala-guice/src/main/scala/KeyExtensions.scala:18: object google is not a member of package com
[error] import com.google.inject._
[error]            ^
[error] /Users/eboto/code/scala-guice/src/main/scala/ScalaModule.scala:18: object google is not a member of package com
[error] import com.google.inject._
[error]            ^
[error] /Users/eboto/code/scala-guice/src/main/scala/ScalaModule.scala:60: value binder is not a member of AnyRef with ScalaObject
[error]   private def binderAccess = super.binder // shouldn't need super
[error]                                    ^
[error] /Users/eboto/code/scala-guice/src/main/scala/binder/BindingProxies.scala:19: object google is not a member of package com
[error] import com.google.inject._
[error]            ^
[error] /Users/eboto/code/scala-guice/src/main/scala/package.scala:20: object google is not a member of package com
[error]     import com.google.inject._
[error]                ^
[error] 7 errors found
[info] == compile ==
[error] Error running compile: Compilation failed
[info] 
[info] Total time: 10 s, completed Jan 23, 2012 4:35:51 PM
> 
```

**Comment by benlings** [comment]
Erem - with sbt, you need to first 'update' before compiling:

`[ben@localhost scala-guice] (master)$ ./sbt update
Getting net.java.dev.jna jna 3.2.3 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    1 artifacts copied, 0 already retrieved (838kB/91ms)
Getting Scala 2.7.7 ...
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    2 artifacts copied, 0 already retrieved (9911kB/1164ms)
Getting org.scala-tools.sbt sbt_2.7.7 0.7.7 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    17 artifacts copied, 0 already retrieved (4379kB/567ms)
[info] Recompiling project definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
Getting Scala 2.9.0-1 ...
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    4 artifacts copied, 0 already retrieved (20447kB/2051ms)
[info] Building project Scala Guice 0.1 against Scala 2.9.0-1
[info]    using ScalaGuice with sbt 0.7.7 and Scala 2.7.7
[info] 
[info] == update ==
[info] :: retrieving :: uk.me.lings#scala-guice_2.9.0-1 [sync]
[info]  confs: [compile, runtime, test, provided, system, optional, sources, javadoc]
[info]  3 artifacts copied, 0 already retrieved (2598kB/232ms)
[info] == update ==
[success] Successful.
[info] 
[info] Total time: 2 s, completed Feb 24, 2012 11:53:03 PM
[info] 
[info] Total session time: 14 s, completed Feb 24, 2012 11:53:03 PM
[success] Build completed successfully.
[ben@localhost scala-guice] (master)$ ./sbt compile
[info] Building project Scala Guice 0.1 against Scala 2.9.0-1
[info]    using ScalaGuice with sbt 0.7.7 and Scala 2.7.7
[info] 
[info] == compile ==
[info]   Source analysis: 6 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling main sources...
[info] Compilation successful.
[info]   Post-analysis: 37 classes.
[info] == compile ==
[success] Successful.
[info] 
[info] Total time: 14 s, completed Feb 24, 2012 11:53:24 PM
[info] 
[info] Total session time: 15 s, completed Feb 24, 2012 11:53:24 PM
[success] Build completed successfully.`

Do you have any suggestions what documentation you would find useful for this?
